# Generated by Django 5.2.1 on 2025-05-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="stock",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, default=10, upload_to="menu_images/"),
            preserve_default=False,
        ),
    ]
