# Generated by Django 5.2.1 on 2025-05-17 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_menuitem_stock_alter_menuitem_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="ordered_at",
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
