# Generated by Django 5.2.1 on 2025-05-17 20:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
