# Generated by Django 5.2.1 on 2025-05-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_item_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_images/"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
