# Generated by Django 5.2.1 on 2025-05-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_delete_item_alter_menuitem_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                choices=[("hot", "Hot"), ("cold", "Cold"), ("bakery", "Bakery")],
                default="hot",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
