# Generated by Django 5.2.1 on 2025-05-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_menuitem_category_alter_menuitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_discounted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
